# Generated by Django 2.1.7 on 2020-01-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='remote_asset',
        ),
        migrations.AddField(
            model_name='project',
            name='asset',
            field=models.FileField(blank=True, upload_to='static/pages/user_assets'),
        ),
    ]
