# Generated by Django 2.1.7 on 2019-03-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment_file',
            field=models.FilePathField(blank=True, match='foo.*', path='/home/images', recursive=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cited_source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='paper',
            field=models.TextField(blank=True),
        ),
    ]
