# Generated by Django 2.1.7 on 2020-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200127_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='asset',
        ),
        migrations.AddField(
            model_name='project',
            name='drive_folder_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
